### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by ghost** [leggedrobotics/radiance_field_ros#1]
Hello, may I ask how to import robot data into this project? Thank you very much!

**Comment by maxwildersmith** [comment]
So this is intended to run as a ROS 1 Noetic node (can follow the setup instructions in the [ReadMe](https://github.com/leggedrobotics/radiance_field_ros?tab=readme-ov-file#installation)). Once installed in a catkin workspace it needs to be linked to your NerfStudio install (instructions also in the ReadMe). You can check the installation by running `ns-ros -h` which should print out the help text as well a the detected methods.

Then create or modify a config file ([samples](https://github.com/leggedrobotics/radiance_field_ros/tree/main/ros_nerf/config)) to specify what topics you want to subscribe to and what hyperparameters you want to set.

Then with either your ROS stack running for your robot, or a ROS bag with prerecorded data running, run `ns-ros <model-name> --config_path <config_file> [OPTIONS]`. By default the Viser viewer and action server will be running so you can view the model by clicking viewer link in the terminal, or using the RViz plugin.

Hope this helps!
