### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by huzhanxiaoxue** [leggedrobotics/radiance_field_ros#2]
Is there a relevant dataset to run

**Comment by maxwildersmith** [comment]
Yes! We will be releasing public datasets before IROS 2024, they will be ROS bags meant to run with sample configuration files currently in the repo.

**Comment by maxwildersmith** [comment]
Updated the readme to include a datasets folder. The ROS bags can be found [here ](https://drive.google.com/drive/folders/1_Z-Z5WJOUWyvzGk0lrY_ORTcB7Wi2xQw). Hope this helps!
