### ISSUE TITLE
something going wrong with command "ns-ros-save" 

### ISSUE THREAD

**Issue by Ian-YJX** [leggedrobotics/radiance_field_ros#4]
When I ran the command "ns-ros-save", an error appeared. Hope someone could help solve the problem. Thanks a lot. 
![image](https://github.com/user-attachments/assets/ac2afb61-12b4-4783-b0f5-f30844d82188)

**Comment by maxwildersmith** [comment]
Thank you letting me know, the broken script has been corrected.

**Comment by Ian-YJX** [comment]
This works! Thank you
