### ISSUE TITLE
Switch.bag

### ISSUE THREAD

**Issue by Ian-YJX** [leggedrobotics/radiance_field_ros#5]
It seems that the switch.bag cannot work well on my computer. 
![截图 2024-09-24 09-57-53](https://github.com/user-attachments/assets/12d3ea22-455f-4ba3-b89f-67f8567ebb14)
What can I do to solve this problem? Or could anyone help me, please? Thanks

**Comment by maxwildersmith** [comment]
Thanks! Should be working again as of e5afc2c .

**Comment by Ian-YJX** [comment]
Thanks a lot! But here's another problem. When I opened RViz, The rendering result looked dissatisfactory. I used Nvidia 4060 GPU, so I think it's not the GPU's problem. Hope you could help me,thanks.

**Comment by Ian-YJX** [comment]
[录屏 2024-09-27 12-25-32.webm](https://github.com/user-attachments/assets/69a205fa-7cd7-4f1f-be22-c6419dd8d34a)

**Comment by Ian-YJX** [comment]
![截图 2024-09-27 09-45-21](https://github.com/user-attachments/assets/a545d67d-8d2b-4ae0-801b-f4ccc91a27dc)
![截图 2024-09-27 18-42-59](https://github.com/user-attachments/assets/935bd3cb-f629-4bc8-9d69-e0cac140a747)
Here's some more details.

**Comment by Ian-YJX** [comment]
Ah! I figured it out myself. Sorry for interrupting and thank you again for this amazing work!
