### ISSUE TITLE
Something wrong with environment configuration

### ISSUE THREAD

**Issue by Ian-YJX** [leggedrobotics/radiance_field_ros#6]
I successfully configured the conda environment before, but now I am using another computer with a better GPU, and I faced a problem like this, hope somebody could help me, thanks.
![2024-10-21 17-13-52屏幕截图](https://github.com/user-attachments/assets/3a71d919-4f3d-4f44-adc0-132911153829)

**Comment by maxwildersmith** [comment]
Unfortunately I am not able to replicate this issue, but you might try completely uninstalling pymeshlab, and reinstalling. Maybe try the steps linked in [this NerfStudio issue](https://github.com/nerfstudio-project/nerfstudio/issues/1176).

**Comment by Ian-YJX** [comment]
Thank you again for your patience and great work. I will try to solve it according to the link.
