### ISSUE TITLE
Perspective problem

### ISSUE THREAD

**Issue by Ian-YJX** [leggedrobotics/radiance_field_ros#8]
The 3D reconstruction effect is good, but the perspective remains unchanged. What should I do to make the perspective of the 3D reconstruction result consistent with the current camera input perspective

**Comment by maxwildersmith** [comment]
Do you mean the camera FOV/position? and in which viewer? RViz, Viser, or some other viewer?

**Comment by Ian-YJX** [comment]
In Rviz

**Comment by maxwildersmith** [comment]
Ah, for position, you could manually change the position for the view controller (in the right hand panel) to track the camera's frame as the target frame, then zero out the position and rotation, and that should get you to roughly the same position.

If its an issue with FOV (say a wide angle camera) I'm afraid thats currently not implemented as the viewing camera is the same as the RViz default FOV, if you want to dig in to the plugin code, you should be able to change both the RViz FOV and render FOV or break that out as a slot.

**Comment by Ian-YJX** [comment]
And what’s the camera frame’s name? I found the viewer panel in the right hand, but couldn’t find out the exact name of the frame.

**Comment by maxwildersmith** [comment]
that would be whatever camera you have in your TF tree, it should be the frame in the yaml file for data collection, or in the image's header. If you are stuck in a cloud or noisy space and trying to find roughly where the scene is, I recommend enabling TF/RobotDescription so you can see where the robot is.

If you are looking to see what the render looks like compared to GT, you can also toggle evaluation data (`--vis viewer+tensorboard` or `--vis viewer+wandb` to log metrics for comparisons), if you are looking to watch the images render while training, you can also try the viser viewer (should be at http://localhost:8080/).

**Comment by maxwildersmith** [comment]
Hey there!

Are you still having issues with this?
